services:
  - type: web
    name: rag-pdf-qa-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false

